
version: "3.8"
services:
  ph3-posseapp-web:
    platform: linux/amd64
    build:
      context: ./container/web
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80

  ph3-posseapp-app:
    platform: linux/amd64
    build:
      context: ./container/app
    volumes:
      - ./src:/var/www/html

  ph3-posseapp-db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - ./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./container/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./container/db/data:/var/lib/mysql
